### ISSUE TITLE
Missing header in `Aria/ariaTypedefs.h`

### ISSUE THREAD

**Issue by joaocandre** [reedhedges/AriaCoda#12]
In order to use the standard integer types `std::int8_t`, etc the system header `cstdint` needs to be included, otherwise building will fail (you end up with an ungodly amount of `<...> not declared in this scope` errors).

I can make a PR if you like, but it's a simple fix, just add the missing include `#include <cstdint>` to `ariaTypedefs.h`

(Tested on an up-to-date Arch Linux installation, GCC v. 13.2.1)

**Comment by reedhedges** [comment]
Thank you!   Fixed now in HEAD by adding `#include <cstdint>`.  

It looks like none of the test or example programs use `ArTypes`, it would be good to have a test program that covers some or most of the small utilities like these...  test coverage in Aria was always a bit spotty (the tests are really manual tests either development/debugging aids or meant to produce some behavior when connected to a robot.)  I'll think about either adding it or mentioning this in the TODO.txt file.
